# This workflow will install a prebuilt Ruby version, install dependencies, and
# run tests and linters.
name: "Rails CI/CD"
on:
  push:
    paths-ignore:
      - .gitignore
      - README.md
      - LICENSE
  pull_request:
    types: [opened, reopened]
  merge_group:
    types: [checks_requested]
  workflow_dispatch:
  
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install Ruby and gems
        uses: ruby/setup-ruby@8f312efe1262fb463d906e9bf040319394c18d3e # v1.92
        with:
          bundler-cache: true
      - name: Security audit dependencies
        run: bundle exec bundle audit --update
      - name: Security audit application code
        run: bundle exec brakeman -q -w2
      - name: Lint Ruby files
        run: bundle exec rubocop --parallel

  # test:
  #   runs-on: ubuntu-latest
  #   services:
  #     postgres:
  #       image: postgres:11-alpine
  #       ports:
  #         - "5432:5432"
  #       env:
  #         POSTGRES_DB: rails_test
  #         POSTGRES_USER: rails
  #         POSTGRES_PASSWORD: password
  #   env:
  #     RAILS_ENV: test
  #     DATABASE_URL: "postgres://rails:password@localhost:5432/rails_test"
  #   steps:
  #     - name: Checkout code
  #       uses: actions/checkout@v3
  #     # Add or replace dependency steps here
  #     - name: Install Ruby and gems
  #       uses: ruby/setup-ruby@8f312efe1262fb463d906e9bf040319394c18d3e # v1.92
  #       with:
  #         bundler-cache: true
  #     # Add or replace database setup steps here
  #     - name: Set up database schema
  #       run: bin/rails db:schema:load
  #     # Add or replace test runners here
  #     - name: Run tests
  #       run: bundle exec rspec
